name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 6 * * *

jobs:
  Test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.0
          - 7.3
        dependencies:
          - hi
          - lo

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json
        run: composer validate

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: php-${{ matrix.php }}-${{ matrix.dependencies }}-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php }}-${{ matrix.dependencies }}-

      - name: Install dependencies ${{ matrix.dependencies == 'lo' && '(lowest)' || '' }}
        run: composer update --no-interaction --no-progress
          ${{ matrix.dependencies == 'lo' && '--prefer-lowest' || '' }}

      - name: Run test suite
        run: composer test
